### ISSUE TITLE
Incompatible with Firefox on Android

### ISSUE THREAD

**Issue by ellis2323** [teckel12/vue-barcode-reader#11]
If you test your demo with firefox on Android, it flashes w/o scan. Otherwise, on chrome / S21FE, the scanner doesn't show up. I suspect the cycle of camera.

**Comment by teckel12** [comment]
@ellis2323 When I try Firefox, the screen goes black, the camera wakes up (shows in my title bar) but it doesn't ever show the camera, even when I allow all camera permissions.  Firefox then crashes after about 30 seconds.  It appears there's either a bug with Android Firefox or it's not accessing the cameras in the same standard way as Chrome and Safari.

Can't really debug Firefox on Android, so I installed it on MacOS and it displays the same black screen with no camera.  But it also creates some kind of loop which consumed 42GB of RAM and my computer was extremely slow.  Seems there's a huge memory leak with both the Android and MacOS version of Firefox.

**Comment by teckel12** [comment]
@ellis2323 I get no console messages when using Firefox on MacOS, it just eats all RAM and slows my computer to a crawl till it crashes.  My guess is that's what's happening with Firefox on Android why it just flashes for you.  For me, it tries, but then crashes, it's probably crashing sooner for you.

Not sure what to do about this, seems like a fairly drastic Firefox bug as a website shouldn't be able to kill the app or take down the computer.  I have no experience with Firefox to report this or to who.

**Comment by ellis2323** [comment]
On firefox, there's no torch API. When we use your version (not the original one), it seems there's a loop trying to detect camera.

**Comment by ellis2323** [comment]
I have tested this library with success: html5-qrcode. It check camera, torch like you did and share many code with you. It works on Firefox android (but w/o torch which is normal).

**Comment by ellis2323** [comment]
Not sure if it can help you:

```Debugging Firefox on iOS can be done using Safari’s Web Inspector. Here are the steps to get started:

Enable “Web Inspector” on your iOS device by going to “Settings” > “Safari” > “Advanced” and turning on “Web Inspector.”

Connect your iOS device to your Mac using a USB cable.

Open Firefox on your iOS device and navigate to the website you want to debug.

On your Mac, open Safari and go to “Preferences” > “Advanced” and check “Show Develop menu in menu bar.”

From the “Develop” menu in Safari, select your iOS device and choose the website you want to debug.

The website will now open in Safari’s Web Inspector. You can use the Web Inspector to inspect the HTML, CSS, and JavaScript of the website, as well as view console logs and network requests.

Note that not all features of Firefox may be available for debugging in Safari’s Web Inspector, and some debugging tasks may require additional tools or resources.
```

**Comment by teckel12** [comment]
@ellis2323 Firefox works just fine on iOS (well, at least on an iPad, which is the only iOS device I have).  So the debug instructions isn't helpful.  Also to clarify, it doesn't turn on the torch by default.  It just detects if it's available, and if so there's a button to turn it on or off.  So my guess it's locking up in the camera device detection phase.

**Comment by teckel12** [comment]
@ellis2323 I was able to debug the problem.  The issue was that Firefox doesn't support the function getCapabilities() so it was failing and causing an endless loop.  It's still odd that it would use all available RAM from and endless loop, but in any case, it's resolved in v1.1.5 which I'm getting online now.

**Comment by ellis2323** [comment]
Great. Thanks for your hard work.

**Comment by teckel12** [comment]
[v1.1.5](https://github.com/teckel12/vue-barcode-reader/releases/tag/1.1.5) resolves the problem
