### ISSUE TITLE
[feature] Change FPS

### ISSUE THREAD

**Issue by ellis2323** [teckel12/vue-barcode-reader#13]
Hello,

I have implemented in my application, your scanner and another one. The second seems have better scan response because I can specify to scan at 10fps (default is 2). On yours, i do not see how to set up video capture fps ?

**Comment by teckel12** [comment]
@ellis2323 Fairly simple to setup, but not sure how much of a benefit it would provide.  The default is 500ms between scans.  I changed it to 100ms and didn't notice a difference.  You can try it out here:

https://github.com/teckel12/vue-barcode-reader/tree/1.1.6
https://github.com/teckel12/vue-barcode-reader/pull/14

**Comment by teckel12** [comment]
@ellis2323 Now merged

**Comment by ellis2323** [comment]
Perfect. I have tested with 50ms. It seems (but it's difficult to be certain) faster to scan bibs (used in running).

**Comment by teckel12** [comment]
@ellis2323 As an avid runner, would love to know more about your bib project using this library.

**Comment by teckel12** [comment]
Feature merged
