### ISSUE TITLE
demo not working in ios 17.4.1

### ISSUE THREAD

**Issue by conx13** [teckel12/vue-barcode-reader#18]
Hei, demo page iphone(12) 17.4.1 - asks for permission and then has a black blank screen...
Works on ipad.

**Comment by teckel12** [comment]
Thanks, will look into this.

**Comment by cylwin** [comment]
If it can help on ios17 :
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 't[o].focusMode.includes')

**Comment by teckel12** [comment]
Resolved in v1.1.7

**Comment by teckel12** [comment]
Resolved in v1.1.7
