### ISSUE TITLE
Problem with IOS 16.5.1 - Iphone 12 & 11

### ISSUE THREAD

**Issue by alvarobertin** [teckel12/vue-barcode-reader#6]
I have tested the example page on a SAMSUNG Galaxy S20 FE and it works perfect. 

The only problem is with the autofocus that does not work on an Iphone 12 Pro Max with IOS 16.5.1 and also does not work with Iphone 11 with IOS 16.5.1.

![test](https://github.com/teckel12/vue-barcode-reader/assets/50723409/e024319c-89f1-4320-977f-9c4a3a2cad35)

**Comment by teckel12** [comment]
@alvarobertin If you could try again using the latest version and the latest demo which is here:

https://barcode.leethost.com/

Also note that on iOS there will be less features available as Apple doesn't expose certain features that can be activated and controlled.  About the only thing which will work on iOS is switching between different camera devices, which is probably what's happening in your case (it selected a device that doesn't have autofocus).  The latest demo version shown above should have an additional icon a the top allowing you to switch camera devices.

Let me know!  The only iOS device I have is an iPad Mini, so iPhone testing has been limited to others testing it for me.

**Comment by teckel12** [comment]
@alvarobertin I assume this is now working.  This issue will be closed in 7 days if there's no additional information.

**Comment by alvarobertin** [comment]
Yeah, now is working perfectly and we are using it on prod! thanks!
